Алексашин А.С. 6303 Lab2
RumyantS97/MSDT pull request #48
Opened 2024-10-27 13:00 UTC by RumyantS97

ФИО: Алексашин А.С. @iHlpNw
Номер группы: 6303
Описание: Одна из имплементаций 3 лабораторной по ОИБ, написанная много лет назад. Необходимо выделить проблемы данного кода и предложить варианты их решения

2024-10-30 15:34 UTC, iHlpNw requested changes
Code review

2024-10-30 15:34 UTC, iHlpNw commented on msdt-2/main.py
> +from tqdm.notebook import tqdm_notebook
Не используется

2024-10-30 15:34 UTC, iHlpNw commented on msdt-2/main.py
> +from cryptography.hazmat.primitives import padding as padding2
Объединить импорты, имеющие одинаковый путь

2024-10-30 15:34 UTC, iHlpNw commented on msdt-2/main.py
> +def key_generation(symmetric_key_path: str, public_key_path: str, secret_key_path: str) -> None:
Название метода не соответствует стандарту

2024-10-30 15:34 UTC, iHlpNw commented on msdt-2/main.py
> +    with tqdm(100, desc='Generation keys') as prograssbar:
Следует указать ключевое слово total

2024-10-30 15:34 UTC, iHlpNw commented on msdt-2/main.py
> +    with tqdm(100, desc='Generation keys') as prograssbar:
Название переменной prograssbar следует скорректировать

2024-10-30 15:34 UTC, iHlpNw commented on msdt-2/main.py
> +        public_key = keys.public_key()
Промежуточная переменная keys является излишней

2024-10-30 15:34 UTC, iHlpNw commented on msdt-2/main.py
> +        public_pem = public_key_path + '\\key.pem'
Более целесообразно использовать os.path.join для создания путей файлов

2024-10-30 15:34 UTC, iHlpNw commented on msdt-2/main.py
> +                                                     format=serialization.PublicFormat.SubjectPublicKeyInfo))
Промежуточная переменная public_pem здесь не нужна.

2024-10-30 15:34 UTC, iHlpNw commented on msdt-2/main.py
> +                                                        encryption_algorithm=serialization.NoEncryption()))
Промежуточная переменная private_pem здесь не нужна

2024-10-30 15:34 UTC, iHlpNw commented on msdt-2/main.py
> +            key_file.write(encrypted_symmetric_key)
Промежуточная переменная symmetric_file является излишней

2024-10-30 15:34 UTC, iHlpNw commented on msdt-2/main.py
> +    symmetric_file = symmetric_key_path + '\\key.txt'
os.path.join целесообразней

2024-10-30 15:34 UTC, iHlpNw commented on msdt-2/main.py
> +        encrypted_symmetric_key = key_file.read()
symmetric_file промежуточна

2024-10-30 15:34 UTC, iHlpNw commented on msdt-2/main.py
> +    private_pem = secret_key_path + '\\key.pem'
os.path.join

2024-10-30 15:34 UTC, iHlpNw commented on msdt-2/main.py
> +    private_key = load_pem_private_key(private_bytes, password=None)
private_pem - промежуточная

2024-10-30 15:34 UTC, iHlpNw commented on msdt-2/main.py
> +        initial_content = _file.read()
os.path.join
initial_file - промежуточная
Название переменной _file

2024-10-30 15:34 UTC, iHlpNw commented on msdt-2/main.py
> +        yaml.dump(dict_t, _file)
os.path.join
encrypted_file - промежуточная
Название переменной _file

2024-10-30 15:34 UTC, iHlpNw commented on msdt-2/main.py
> +def decrypting_data(encrypted_file_path: str, secret_key_path: str, symmetric_key_path: str,
Название метода не соответствует стандарту

2024-10-30 15:34 UTC, iHlpNw commented on msdt-2/main.py
> +        encrypted_symmetric_key = key_file.read()
os.path.join
symmetric_file - промежуточная

2024-10-30 15:34 UTC, iHlpNw commented on msdt-2/main.py
> +    with open(private_pem, 'rb') as pem_in:
os.path.join
private_pem - промежуточная

2024-10-30 15:34 UTC, iHlpNw commented on msdt-2/main.py
> +        content_encrypted = yaml.safe_load(_file)
os.path.join
промежуточная переменная
Название _file

2024-10-30 15:34 UTC, iHlpNw commented on msdt-2/main.py
> +        _file.write(str(unpadded_dc_text))
os.path.join
Промежуточная переменная
Название _file

2024-10-30 15:34 UTC, iHlpNw commented on msdt-2/main.py
> +    with tqdm(100, desc='Encryption mode') as prograssbar:
prograssbar -> progress_bar
Следует указать ключевое слово total для значения '100'

2024-10-30 15:34 UTC, iHlpNw commented on msdt-2/main.py
> +    with tqdm(100, desc='Decryption mode') as prograssbar:
prograssbar -> progress_bar.
Следует указать ключевое слово total

2024-10-30 15:34 UTC, iHlpNw commented on msdt-2/main.py
Подкорректировать длину строк

2024-10-30 15:34 UTC, iHlpNw commented on msdt-2/main.py
> +    with open(encrypted_file) as _file:
В open() следует явно указать "rb"

2024-10-31 14:47 UTC, RumyantS97 commented
Зачтено

2024-10-31 14:47 UTC, closed without merging